qywx:
  # 企业 ID
  cropid: xxxxx
  application:
    # 文本发送接口
    alarm:
      port: 18889
    # API 接收消息服务器接口
    openapi:
      port: 18888
      # Token
      token: xxxxxx
      # EncodingAESKey
      key: xxxxx

# 存储企业微信 access_token
redis:
  # redis ip address
  host: 127.0.0.1
  # redis tcp port
  port: 6379
  # redis auth password
  password: xxxxx
